### ISSUE TITLE
fail to compile with errors inside ubuntu 22.04 docker

### ISSUE THREAD

**Issue by ouvaa** [litespeedtech/lsquic#498]
possible to provide the instructions to compile lsquic inside ubuntu 22.04 docker container?

```
root@uwebsocket:/usr/local/src/boringssl# cd lsquic/
root@uwebsocket:/usr/local/src/boringssl/lsquic# cmake -DBORINGSSL_DIR=$BORINGSSL .
-- CMake v3.22.1
-- Build type: Debug
-- AddressSanitizer is OFF
-- Compiler flags:   -fPIC  -DLSQUIC_DEBUG_NEXT_ADV_TICK=1 -DLSQUIC_CONN_STATS=1 -Wall -Wextra -Wno-unused-parameter -fno-omit-frame-pointer -Wno-missing-field-initializers -O0 -g3 
-- BoringSSL include directory /usr/local/src/boringssl/include
-- Found ssl library: /usr/local/src/boringssl/ssl/libssl.a
-- Found crypto library: /usr/local/src/boringssl/crypto/libcrypto.a
-- Found zlib: /usr/lib/x86_64-linux-gnu/libz.a
-- Found event: /usr/lib/x86_64-linux-gnu/libevent.a
-- sphinx-build not found: docs won't be made
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/boringssl/lsquic
root@uwebsocket:/usr/local/src/boringssl/lsquic# make
Consolidate compiler generated dependencies of target lsquic
[ 33%] Built target lsquic
Consolidate compiler generated dependencies of target http_server
[ 33%] Linking C executable http_server
/usr/bin/ld: /usr/local/src/boringssl/ssl/libssl.a(ssl_asn1.cc.o):(.data.rel.local.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
/usr/bin/ld: /usr/local/src/boringssl/ssl/libssl.a(ssl_key_share.cc.o): in function `bssl::(anonymous namespace)::X25519KeyShare::~X25519KeyShare()':
/usr/local/src/boringssl/ssl/ssl_key_share.cc:138: undefined reference to `operator delete(void*, unsigned long)'
/usr/bin/ld: /usr/local/src/boringssl/ssl/libssl.a(ssl_key_share.cc.o): in function `bssl::(anonymous namespace)::X25519Kyber768KeyShare::~X25519Kyber768KeyShare()':
/usr/local/src/boringssl/ssl/ssl_key_share.cc:194: undefined reference to `operator delete(void*, unsigned long)'
/usr/bin/ld: /usr/local/src/boringssl/ssl/libssl.a(ssl_key_share.cc.o): in function `bssl::(anonymous namespace)::ECKeyShare::~ECKeyShare()':
/usr/local/src/boringssl/ssl/ssl_key_share.cc:41: undefined reference to `operator delete(void*, unsigned long)'
/usr/bin/ld: /usr/local/src/boringssl/ssl/libssl.a(ssl_key_share.cc.o):(.data.rel.ro._ZTIN4bssl11SSLKeyShareE[_ZTIN4bssl11SSLKeyShareE]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
/usr/bin/ld: /usr/local/src/boringssl/ssl/libssl.a(ssl_key_share.cc.o):(.data.rel.ro+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/bin/ld: /usr/local/src/boringssl/ssl/libssl.a(ssl_key_share.cc.o):(.data.rel.ro+0x18): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/bin/ld: /usr/local/src/boringssl/ssl/libssl.a(ssl_key_share.cc.o):(.data.rel.ro+0x30): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/CMakeFiles/http_server.dir/build.make:150: bin/http_server] Error 1
make[1]: *** [CMakeFiles/Makefile2:289: bin/CMakeFiles/http_server.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

```

**Comment by litespeedtech** [comment]
Please try following the same steps in the update Dockerfile.
